output_dir: ~/scratch/protein_outputs

dataset:
  class: AlphaFoldDB
  path: ~/scratch/protein-datasets/alphafold
  species_start: 48
  species_end: 48
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 100
        random: True

task:
  class: AttributeMaskingByPoints
  mask_rate: 0.15
  num_mlp_layer: 2
  model:
    class: GN
    input_dim: 21
    hidden_dims: [512, 512, 512, 512, 512, 512]
    # hidden_dims: [64, 64, 64, 64, 64, 64]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    # edge_input_dim: 59
    edge_input_dim: 40
    num_angle_bin: 8
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    # edge_feature: gearnet
    edge_feature: residue_type

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 96
  log_interval: 100

save_interval: 5

train:
  num_epoch: 50

logger:
  wandb: True